apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ir
  namespace: {{ .Release.Namespace }}
{{- with .Values.OPENCTI_INGRESS_ANNOTATIONS }}
  annotations:
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.OPENCTI_INGRESS_CLASS }}
  ingressClassName: {{ .Values.OPENCTI_INGRESS_CLASS }}
{{- end }}
  tls:
    - hosts:
      - {{ .Values.OPENCTI_INGRESS_HOST }}
      secretName: {{ .Values.OPENCTI_TLS_SECRET }}
  rules:
    - host: {{ .Values.OPENCTI_INGRESS_HOST }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-opencti
              port:
                number: 8080
